#
# messages
#
#
ghostElement = undefined
startPos = undefined
gCoords = undefined

gotMessage = (request, sender, sendResponse) ->
  if request.type == 'start-screenshots'
    startScreenshot()
  sendResponse {}
  return

startScreenshot = ->
  document.addEventListener 'mousedown', mouseDown, false
  document.addEventListener 'keydown', keyDown, false
  return

endScreenshot = (coords) ->
  document.removeEventListener 'mousedown', mouseDown, false
  sendMessage
    type: 'coords'
    coords: coords
    pageUrl: document.location.href
  return

sendMessage = (msg) ->
  chrome.extension.sendRequest msg, (response) ->
  return

keyDown = (e) ->
  keyCode = e.keyCode
  # Hit: n
  if keyCode == '78' and gCoords
    e.preventDefault()
    e.stopPropagation()
    endScreenshot gCoords
    return false
  return

mouseDown = (e) ->
  e.preventDefault()
  startPos =
    x: e.pageX
    y: e.pageY
  ghostElement = document.createElement('div')
  ghostElement.style.background = 'blue'
  ghostElement.style.opacity = '0.1'
  ghostElement.style.position = 'absolute'
  ghostElement.style.left = e.pageX + 'px'
  ghostElement.style.top = e.pageY + 'px'
  ghostElement.style.width = '0px'
  ghostElement.style.height = '0px'
  ghostElement.style.zIndex = '1000000'
  document.body.appendChild ghostElement
  document.addEventListener 'mousemove', mouseMove, false
  document.addEventListener 'mouseup', mouseUp, false
  false

mouseMove = (e) ->
  e.preventDefault()
  nowPos =
    x: e.pageX
    y: e.pageY
  diff =
    x: Math.abs(nowPos.x - startPos.x)
    y: Math.abs(nowPos.y - startPos.y)
  ghostElement.style.width = diff.x + 'px'
  ghostElement.style.height = diff.y + 'px'
  ghostElement.style.top = Math.min(startPos.y, nowPos.y) + 'px'
  ghostElement.style.left = Math.min(startPos.x, nowPos.x) + 'px'
  false

mouseUp = (e) ->
  e.preventDefault()
  nowPos =
    x: e.pageX
    y: e.pageY
  diff =
    x: Math.abs(nowPos.x - startPos.x)
    y: Math.abs(nowPos.y - startPos.y)
  document.removeEventListener 'mousemove', mouseMove, false
  document.removeEventListener 'mouseup', mouseUp, false
  ghostElement.parentNode.removeChild ghostElement
  setTimeout (->
    r = window.devicePixelRatio
    coords =
      w: diff.x * r
      h: diff.y * r
      x: (Math.min(startPos.x, nowPos.x) - window.scrollX ) * r
      y: (Math.min(startPos.y, nowPos.y) - window.scrollY ) * r
    gCoords = coords
    endScreenshot coords
    return
  ), 50
  false

chrome.extension.onRequest.addListener gotMessage
#
# end messages
#
# ---
# src: https://gist.github.com/erkie/2730276#file-content-js
# generated by js2coffee 2.0.1
